//LeafClass define
#define		abies_concolor	1
#define		abies_nordmanniana	2
#define		acer_campestre	3
#define		acer_ginnala	4
#define		acer_griseum	5
#define		acer_negundo	6
#define		acer_palmatum	7
#define		acer_pensylvanicum	8
#define		acer_platanoides	9
#define		acer_pseudoplatanus	10
#define		acer_rubrum	11
#define		acer_saccharinum	12
#define		acer_saccharum	13
#define		aesculus_flava	14
#define		aesculus_glabra	15
#define		aesculus_hippocastamon	16
#define		aesculus_pavi	17
#define		ailanthus_altissima	18
#define		albizia_julibrissin	19
#define		amelanchier_arborea	20
#define		amelanchier_canadensis	21
#define		amelanchier_laevis	22
#define		asimina_triloba	23
#define		betula_alleghaniensis	24
#define		betula_jacqemontii	25
#define		betula_lenta	26
#define		betula_nigra	27
#define		betula_populifolia	28
#define		broussonettia_papyrifera	29
#define		carpinus_betulus	30
#define		carpinus_caroliniana	31
#define		carya_cordiformis	32
#define		carya_glabra	33
#define		carya_ovata	34
#define		carya_tomentosa	35
#define		castanea_dentata	36
#define		catalpa_bignonioides	37
#define		catalpa_speciosa	38
#define		cedrus_atlantica	39
#define		cedrus_deodara	40
#define		cedrus_libani	41
#define		celtis_occidentalis	42
#define		celtis_tenuifolia	43
#define		cercidiphyllum_japonicum	44
#define		cercis_canadensis	45
#define		chamaecyparis_pisifera	46
#define		chamaecyparis_thyoides	47
#define		chionanthus_retusus	48
#define		chionanthus_virginicus	49
#define		cladrastis_lutea	50
#define		cornus_florida	51
#define		cornus_kousa	52
#define		cornus_mas	53
#define		corylus_colurna	54
#define		crataegus_crus-galli	55
#define		crataegus_laevigata	56
#define		crataegus_phaenopyrum	57
#define		crataegus_pruinosa	58
#define		crataegus_viridis	59
#define		cryptomeria_japonica	60
#define		diospyros_virginiana	61
#define		eucommia_ulmoides	62
#define		evodia_daniellii	63
#define		fagus_grandifolia	64
#define		ficus_carica	65
#define		fraxinus_americana	66
#define		fraxinus_nigra	67
#define		fraxinus_pennsylvanica	68
#define		ginkgo_biloba	69
#define		gleditsia_triacanthos	70
#define		gymnocladus_dioicus	71
#define		halesia_tetraptera	72
#define		ilex_opaca	73
#define		juglans_cinerea	74
#define		juglans_nigra	75
#define		juniperus_virginiana	76
#define		koelreuteria_paniculata	77
#define		larix_decidua	78
#define		liquidambar_styraciflua	79
#define		liriodendron_tulipifera	80
#define		maclura_pomifera	81
#define		magnolia_acuminata	82
#define		magnolia_denudata	83
#define		magnolia_grandiflora	84
#define		magnolia_macrophylla	85
#define		magnolia_soulangiana	86
#define		magnolia_stellata	87
#define		magnolia_tripetala	88
#define		magnolia_virginiana	89
#define		malus_angustifolia	90
#define		malus_baccata	91
#define		malus_coronaria	92
#define		malus_floribunda	93
#define		malus_hupehensis	94
#define		malus_pumila	95
#define		metasequoia_glyptostroboides	96
#define		morus_alba	97
#define		morus_rubra	98
#define		nyssa_sylvatica	99
#define		ostrya_virginiana	100
#define		oxydendrum_arboreum	101
#define		paulownia_tomentosa	102
#define		phellodendron_amurense	103
#define		picea_abies	104
#define		picea_orientalis	105
#define		picea_pungens	106
#define		pinus_bungeana	107
#define		pinus_cembra	108
#define		pinus_densiflora	109
#define		pinus_echinata	110
#define		pinus_flexilis	111
#define		pinus_koraiensis	112
#define		pinus_nigra	113
#define		pinus_parviflora	114
#define		pinus_peucea	115
#define		pinus_pungens	116
#define		pinus_resinosa	117
#define		pinus_rigida	118
#define		pinus_strobus	119
#define		pinus_sylvestris	120
#define		pinus_taeda	121
#define		pinus_thunbergii	122
#define		pinus_virginiana	123
#define		pinus_wallichiana	124
#define		platanus_acerifolia	125
#define		platanus_occidentalis	126
#define		populus_deltoides	127
#define		populus_grandidentata	128
#define		populus_tremuloides	129
#define		prunus_pensylvanica	130
#define		prunus_sargentii	131
#define		prunus_serotina	132
#define		prunus_serrulata	133
#define		prunus_subhirtella	134
#define		prunus_virginiana	135
#define		prunus_yedoensis	136
#define		pseudolarix_amabilis	137
#define		ptelea_trifoliata	138
#define		pyrus_calleryana	139
#define		quercus_acutissima	140
#define		quercus_alba	141
#define		quercus_bicolor	142
#define		quercus_cerris	143
#define		quercus_coccinea	144
#define		quercus_falcata	145
#define		quercus_imbricaria	146
#define		quercus_macrocarpa	147
#define		quercus_marilandica	148
#define		quercus_michauxii	149
#define		quercus_montana	150
#define		quercus_muehlenbergii	151
#define		quercus_nigra	152
#define		quercus_palustris	153
#define		quercus_phellos	154
#define		quercus_robur	155
#define		quercus_rubra	156
#define		quercus_shumardii	157
#define		quercus_stellata	158
#define		quercus_velutina	159
#define		quercus_virginiana	160
#define		robinia_pseudo-acacia	161
#define		salix_babylonica	162
#define		salix_caroliniana	163
#define		salix_matsudana	164
#define		salix_nigra	165
#define		sassafras_albidum	166
#define		staphylea_trifolia	167
#define		stewartia_pseudocamellia	168
#define		styrax_japonica	169
#define		styrax_obassia	170
#define		syringa_reticulata	171
#define		taxodium_distichum	172
#define		tilia_americana	173
#define		tilia_cordata	174
#define		tilia_europaea	175
#define		tilia_tomentosa	176
#define		toona_sinensis	177
#define		tsuga_canadensis	178
#define		ulmus_americana	179
#define		ulmus_glabra	180
#define		ulmus_parvifolia	181
#define		ulmus_pumila	182
#define		ulmus_rubra	183
#define		zelkova_serrata	184
